resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: github.com_shirhatti

jobs:
- template: azure-pipelines.yml@MicrosoftIISCommon # Template reference
