name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

pr: none
trigger: none

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: IIS-Github

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEngSS-MicroBuild2022-1ES'
    solution: '**\Compression.sln'
    restoreSolution: 'Compression.sln;IIS-Setup/IIS-Setup.sln'
    productMajor: 1
    productMinor: 0
    signType: 'real'
    indexSourcesAndPublishSymbols: 'true'
    publishArtifactInstallers: 'true'
    publishArtifactSources: 'true'
    whiteListPathForAuthenticodeSign: '$(Build.SourcesDirectory)\IIS-Common\.azure\templates\no_authenticode.txt'
    msbuildArgs: '/p:RunWixToolsOutOfProc=true'
