name: $(Rev:rr)

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-PAT

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEng-MicroBuildV2CustomPool'
    agentPoolDemandTeam: 'IISAdmin'
    solution: '**\Compression.sln'
    productMajor: 1
    productMinor: 0
    signType: 'real'
    indexSourcesAndPublishSymbols: 'true'
    publishArtifactInstallers: 'true'
    publishArtifactSources: 'true'