name: $(Rev:rr)

jobs:
- template: templates\build-template.yml
  parameters:
    agentPoolName: 'VSEng-MicroBuildV2CustomPool'
    agentPoolDemandTeam: 'IISAdmin'
    solution: '**\Compression.sln'
    signType: 'test'
    buildType: 'dev'
    productMajor: 1
    productMinor: 0
    publishInstaller: 'true'