name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

pr:
  - master

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
    - repository: MicrosoftIISCommon
      type: github
      name: Microsoft/IIS.Common
      endpoint: GitHub-IIS-Token

jobs:
- template: .azure\templates\build.yml@MicrosoftIISCommon
  parameters:
    agentPoolName: 'VSEng-MicroBuildV2CustomPool'
    solution: '**\Compression.sln'
    productMajor: 1
    productMinor: 0
    signType: 'test'
    publishArtifactInstallers: 'true'
